### ISSUE TITLE
No module named 'flake8_use_fstring' when trying to install this module.

### ISSUE THREAD

**Issue by DaveScream** [MichaelKim0407/flake8-use-fstring#30] opened 2023-07-29 16:31 UTC
```
D:\ComfyUI_windows_portable>.\python_embeded\python.exe -s -m pip install flake8_use_fstring
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting flake8_use_fstring
  Downloading flake8-use-fstring-1.4.tar.gz (5.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\temp\pip-install-yc8__xhk\flake8-use-fstring_975b3cf9b688463aa46c773a18fa26ed\setup.py", line 3, in <module>
          from flake8_use_fstring import __version__
      ModuleNotFoundError: No module named 'flake8_use_fstring'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

D:\ComfyUI_windows_portable>.\python_embeded\python.exe -s -m pip install flake8-use-fstring
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting flake8-use-fstring
  Downloading flake8-use-fstring-1.4.tar.gz (5.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\temp\pip-install-a1jx5fyg\flake8-use-fstring_96dffe2abcdb4324a6c2b942ba6fa367\setup.py", line 3, in <module>
          from flake8_use_fstring import __version__
      ModuleNotFoundError: No module named 'flake8_use_fstring'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by MichaelKim0407** [comment] 2023-07-29 17:13
Hello,

I could not reproduce your error.

Please specify your Python version. Also, can you please try without `https://pypi.ngc.nvidia.com` and see if the error still occurs?

**Comment by MichaelKim0407** [comment] 2023-07-29 17:36
Since you are using a non-standard Python distribution `D:\ComfyUI_windows_portable>.\python_embeded\python.exe`, I suspect that your Python environment is not properly configured.

Your error indicates that during `pip install`, the installation process could not import Python code from the installation directory. This is not a problem with this library.

I will close this issue for now. Please let me know if there is anything else I can help you with.

**Closed as completed by MichaelKim0407** 2023-07-29 17:36 UTC
